def drawhangman(wrongcount):
  if wrongcount == 0:
    print("--------")
    print("|     | ")
    print("|")
    print("|")
    print("|")
    print("|")
    print("|\______")
  elif wrongcount == 1:
    print("--------")
    print("|     | ")
    print("|     0 ")
    print("|       ")
    print("|       ")
    print("|       ")
    print("|\______")
  elif wrongcount == 2:
    print("--------")
    print("|     | ")
    print("|     0 ")
    print("|     | ")
    print("|       ")
    print("|       ")
    print("|\______")
  elif wrongcount == 3:
    print("--------")
    print("|     | ")
    print("|     0 ")
    print("|    /| ")
    print("|       ")
    print("|       ")
    print("|\______")
  elif wrongcount == 4:
    print("--------")
    print("|     | ")
    print("|     0 ")
    print("|    /|\ ")
    print("|       ")
    print("|       ")
    print("|\______")
  elif wrongcount == 5:
    print("--------")
    print("|     | ")
    print("|     0 ")
    print("|    /|\ ")
    print("|    /  ")
    print("|       ")
    print("|\______")
  elif wrongcount == 6:
    print("--------")
    print("|     | ")
    print("|     0 ")
    print("|    /|\  ")
    print("|    / \  ")
    print("|       ")
    print("|\______")
    print("Oh no! You lose!")
